version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - 'aws dynamodb batch-write-item --request-items file://manual/put-items.json'
artifacts:
  files:
    - '**/*'
