version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - >-
        aws dynamodb put-item --table-name $TABLE_NAME
        file://manual/item.json
artifacts:
  files:
    - '**/*'
