version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      # - aws dynamodb batch-write-item --request-items file://webapp/manual/put-items.json
      - >-
        aws dynamodb put-item --table-name $TABLE_NAME --item file://webapp/manual/item.json
artifacts:
  files:
    - '**/*'
