version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
      - npm install newman --global
      - yum install -y jq
  pre_build:
    commands:
      - >-
        ls -las
      - cd webapp
      - chmod +x *.sh
      - ./update-postman-env-file.sh ${SAM_STACK_NAME}
  build:
    commands:
      - >-
        ls -las
      # - >-
      #   newman run collection.json --environment postman_environment.json -r
      #   junit
# reports:
#   JUnitReports:
#     files:
#       - '**/*'
#     base-directory: newman
artifacts:
  files:
    - '**/*'
