version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - >-
        aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET
        --output-template template-export-get.json
artifacts:
  type: zip
  files:
    - template-export-get.json
